# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" , "test" ]
  pull_request:
    branches: [ "main" , "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --os win Ricca_Uncensor_Plugin.csproj
    - name: Upload dll
      uses: actions/upload-artifact@v4.3.1
      with:
        name: Ricca_Uncensor_Plugin
        path: bin/Debug/net6.0/win-x64/Ricca_Uncensor_Plugin.dll

